### ISSUE TITLE
Missing Rust targets since yesterday

### ISSUE THREAD

**Issue by gnzlbg** [mattgodbolt/compiler-explorer-image#230]
A couple of Rust targets have stopped being available since 30 Jun (e.g. i686-pc-windows-msvc and i686-unknown-linux-gnu, for example). Rust migrated from Travis to Azure and that was the first nightly released in Azure, so chances are that something might have gone wrong. 

Are there any logs available that we could inspect ?

MWE: https://rust.godbolt.org/z/u_ZgbT

**Comment by gnzlbg** [comment]
The last Rust commit appears unrelated (https://github.com/mattgodbolt/compiler-explorer-image/commit/005832d0391046f7a9bbddb4de62f1e8d21d92d2) so this might be an issue on Rust side.

**Comment by apmorton** [comment]
worked around by 4df231f265d7a083f1752f7bd69b6f212a740fd9, although this should be fixed upstream since others will likely experience the same issues with the line endings.

leaving open for now, please let us know when this is resolved upstream and I will revert this workaround and close the issue.

**Comment by gnzlbg** [comment]
Would you mind opening an issue in rust-lang/rust explaining the problem ?

**Comment by RabsRincon** [comment]
This seems to have now been fixed by the rust team and the workaround does not seem to be needed anymore :)
