### ISSUE TITLE
OCaml 4.08.0 not working

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer-image#237]
Was added to -image and main repo, default seems to have been updated, but the version itself is not available.

We should check whether it was correctly installed.

**Comment by apmorton** [comment]
Looks like the compiler was simply never built.
I have stumbled my way through that process, and I think this should be good to go after a few minor issues with the build scripts for ocaml compilers.

@Freyr666 can you confirm the new compiler versions work as expected on the live site?
The `-flambda` version may take a few minutes to appear, but `4.08.0` is up.

@mattgodbolt it doesn't appear as though you have published an `ocaml-builder` image on dockerhub.  I published one myself at [apmorton/ocaml-builder](https://cloud.docker.com/repository/docker/apmorton/ocaml-builder) to get this build going for now.

Also, starting with 4.08 the ocaml `./configure` no longer accepts `-flambda`.  It has been changed to `--enable-flambda` - I have added a [crappy hack](https://github.com/mattgodbolt/compiler-explorer-image/commit/886d1332f49c3d493936260b88da9631bf5c0e24) to the build.sh for now to get that built.

**Comment by Freyr666** [comment]
@apmorton so was it due to `flambda` option? Yes, it works now. I'll try to add a proper fix when 4.08.1 would come out. Could you add your dirty hack for now?

**Comment by apmorton** [comment]
They were missing from the site because Matt simply forgot to build and publish them when merging the PR's.

Some compilers don't require that we manually build them and will simply get automatically installed the following night - he likely thought this was the case for the ocaml compiler.

The flambda issue is nothing you need to worry about when you submit a pr for the next version of ocaml. The hack I made is part of our build infrastructure.

**Comment by mattgodbolt** [comment]
Doops! Sorry :blush:
